let express=require("express")
const { login, reg } = require("../controllers/usercont")
const { addpost, all, postbyid, postbycat } = require("../controllers/postcont")
const { posts, delpost, accept, modify } = require("../controllers/adminpostcon")
let rt=new express.Router()
rt.post("/login",login)
rt.post("/reg",reg)
rt.post("/addpost",addpost)
rt.get("/all",all)
rt.get("/postbyid/:pid",postbyid)
rt.get("/postbycat/:cat",postbycat)
rt.get("/posts",posts)
rt.delete("/delpost/:id",delpost)
rt.get("/accept/:id",accept)
rt.put("/modify",modify)
module.exports=rt
